In [1]:
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# read the data
df = pd.read_csv("Laliga.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 20 columns):
Unnamed: 0     62 non-null object
Unnamed: 1     62 non-null object
Unnamed: 2     62 non-null object
Unnamed: 3     62 non-null object
Unnamed: 4     62 non-null object
Unnamed: 5     62 non-null object
Unnamed: 6     62 non-null object
Unnamed: 7     62 non-null object
Unnamed: 8     62 non-null object
Unnamed: 9     62 non-null object
Unnamed: 10    62 non-null object
Unnamed: 11    62 non-null object
Unnamed: 12    62 non-null object
Unnamed: 13    62 non-null object
Unnamed: 14    62 non-null object
Unnamed: 15    62 non-null object
Unnamed: 16    62 non-null object
Unnamed: 17    62 non-null object
Unnamed: 18    62 non-null object
Unnamed: 19    62 non-null object
dtypes: object(20)
memory usage: 9.8+ KB

In [3]:
# correcting column names
df.columns = df.iloc[0]
df = df.reindex(df.index.drop(0))

In [4]:
df.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1

# 1. Read the data set and replace dashes with 0 to make sure you can perform arithmetic operations on the data. (2.5 points)

In [5]:
# Generating numeric value out of Debut and Since/LastApp 
# (example - 1931-32 will be converted to 1931 for numeric calculations)
df['Debut_year'] = df['Debut'].str.split('-').str.get(0)
df['LastApp_year'] = df['Since/LastApp'].str.split('-').str.get(0)
# replacing dashes in absolute numeric fields
cols = ['Seasons', 'Points', 'GamesPlayed', 'GamesWon', 'GamesDrawn', 'GamesLost', 'GoalsFor', 'GoalsAgainst', 
       'Champion', 'Runner-up', 'Third', 'Fourth', 'Fifth', 'Sixth', 'T', 'BestPosition', 'Debut_year', 'LastApp_year']
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
# replacing NANs with zero as suggested
df = df.fillna(0)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61 entries, 1 to 61
Data columns (total 22 columns):
Pos              61 non-null object
Team             61 non-null object
Seasons          61 non-null int64
Points           61 non-null float64
GamesPlayed      61 non-null float64
GamesWon         61 non-null float64
GamesDrawn       61 non-null float64
GamesLost        61 non-null float64
GoalsFor         61 non-null float64
GoalsAgainst     61 non-null float64
Champion         61 non-null float64
Runner-up        61 non-null float64
Third            61 non-null float64
Fourth           61 non-null float64
Fifth            61 non-null float64
Sixth            61 non-null float64
T                61 non-null float64
Debut            61 non-null object
Since/LastApp    61 non-null object
BestPosition     61 non-null int64
Debut_year       61 non-null int64
LastApp_year     61 non-null int64
dtypes: float64(14), int64(4), object(4)
memory usage: 11.0+ KB

# 2. Print all the teams which have started playing between 1930-1980. (5 points)

In [7]:
# Filtering teams which started playing between 1930-1980, both years inclusive
df_between1930_1990 = df.loc[(df["Debut_year"] > 1929) & (df["Debut_year"] < 1981)]

In [8]:
print("Teams which have started playing between 1930-1980:")
df_between1930_1990['Team']

Teams which have started playing between 1930-1980:

4                Valencia
6                 Sevilla
9                Zaragoza
10             Real Betis
11    Deportivo La Coruna
12             Celta Vigo
13             Valladolid
15         Sporting Gijon
16                Osasuna
17                 Malaga
18                 Oviedo
19               Mallorca
20             Las Palmas
22                Granada
23         Rayo Vallecano
24                  Elche
26               Hercules
27               Tenerife
28                 Murcia
29                 Alaves
30                Levante
31              Salamanca
32               Sabadell
33                  Cadiz
35              Castellon
38                Cordoba
40             Recreativo
41              Burgos CF
42             Pontevedra
47              Gimnastic
50               Alcoyano
51                   Jaen
53             AD Almeria
55                 Lleida
58                 Condal
59        Atletico Tetuan
60       Cultural Leonesa
Name: Team, dtype: object

# 3. Print the list of teams which came Top 5 in terms of points (2.5 points)

In [9]:
# filtering top 5 in terms of points
df_top5_points = df.sort_values('Points',ascending = False).head(5)

In [10]:
print('Teams which came Top 5 in terms of points:')
df_top5_points.iloc[:, 1:5]

Teams which came Top 5 in terms of points:

0             Team  Seasons  Points  GamesPlayed
1      Real Madrid       86  4385.0       2762.0
2        Barcelona       86  4262.0       2762.0
3  Atletico Madrid       80  3442.0       2614.0
4         Valencia       82  3386.0       2664.0
5  Athletic Bilbao       86  3368.0       2762.0

# 4. Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. Using the same function, find the team which has maximum and minimum goal difference. (5 points)

In [11]:
# function definition
def Goal_diff_count(GoalsFor,GoalsAgainst):
    diff = GoalsFor - GoalsAgainst
    return diff

In [12]:
# calculating goal difference using function defined above
df['Goal_diff'] = Goal_diff_count(df['GoalsFor'], df['GoalsAgainst'])
team_maxGD = df.sort_values('Goal_diff',ascending = False).head(1)
team_minGD = df.sort_values('Goal_diff',ascending = True).head(1)

In [13]:
print('Team which has maximum goal difference:')
team_maxGD.iloc[:, [1,2,8,9,22]]
print('Team which has minimum goal difference:')
team_minGD.iloc[:, [1,2,8,9,22]]

Team which has maximum goal difference:

0         Team  Seasons  GoalsFor  GoalsAgainst  Goal_diff
1  Real Madrid       86    5947.0        3140.0     2807.0

Team which has minimum goal difference:

0               Team  Seasons  GoalsFor  GoalsAgainst  Goal_diff
14  Racing Santander       44    1843.0        2368.0     -525.0

# 5. Create a new column with name “Winning Percent” and append it to the data set (5 points)
# If there are any numerical error, replace it with 0%
# Print the top 5 teams which has the highest Winning percentage

In [14]:
df['Winning_Percent'] =  (df['GamesWon'] / df['GamesPlayed'])*100

In [15]:
#NOTE: New column Winning_Percent above has only 60 non-null values, is float64 otherwise. 
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61 entries, 1 to 61
Data columns (total 24 columns):
Pos                61 non-null object
Team               61 non-null object
Seasons            61 non-null int64
Points             61 non-null float64
GamesPlayed        61 non-null float64
GamesWon           61 non-null float64
GamesDrawn         61 non-null float64
GamesLost          61 non-null float64
GoalsFor           61 non-null float64
GoalsAgainst       61 non-null float64
Champion           61 non-null float64
Runner-up          61 non-null float64
Third              61 non-null float64
Fourth             61 non-null float64
Fifth              61 non-null float64
Sixth              61 non-null float64
T                  61 non-null float64
Debut              61 non-null object
Since/LastApp      61 non-null object
BestPosition       61 non-null int64
Debut_year         61 non-null int64
LastApp_year       61 non-null int64
Goal_diff          61 non-null float64
Winning_Percent    60 non-null float64
dtypes: float64(16), int64(4), object(4)
memory usage: 11.9+ KB

In [16]:
# replacing NANs with zero as suggested
df = df.fillna(0)

In [17]:
print('Top 5 teams which has the highest Winning percentage:')
top5_winperc = df.sort_values('Winning_Percent',ascending = False).head(5)
top5_winperc.iloc[:, [1,2,4,5,23]]

Top 5 teams which has the highest Winning percentage:

0             Team  Seasons  GamesPlayed  GamesWon  Winning_Percent
1      Real Madrid       86       2762.0    1647.0        59.630702
2        Barcelona       86       2762.0    1581.0        57.241130
3  Atletico Madrid       80       2614.0    1241.0        47.475134
4         Valencia       82       2664.0    1187.0        44.557057
5  Athletic Bilbao       86       2762.0    1209.0        43.772629

# 6. Group teams based on their “Best position” and print the sum of their points for all positions (10 points)

In [18]:
# Group by best position
best_position = df.groupby("BestPosition")["Points"].agg("sum")

print("Sum of grouped teams' points for all positions:")
pd.DataFrame({'BestPosition':best_position.index, 'Points':best_position.values})

Sum of grouped teams' points for all positions:

    BestPosition   Points
0              1  27933.0
1              2   6904.0
2              3   5221.0
3              4   6563.0
4              5   1884.0
5              6   2113.0
6              7   1186.0
7              8   1134.0
8              9     96.0
9             10    450.0
10            11    445.0
11            12    511.0
12            14     71.0
13            15     14.0
14            16     81.0
15            17    266.0
16            19     81.0
17            20     34.0